### ISSUE TITLE
Missing seeds from canvas:install

### ISSUE THREAD

**Issue by austintoddj** [cnvs/easel#10]
On the `develop` branch, the following lines were removed from the install command:

```
// Database Setup
if (! (Schema::hasTable('migrations') && Schema::hasTable('users'))) {
    $this->comment(PHP_EOL.'Creating your database...');
    $exitCode = Artisan::call('migrate', [
        '--seed' => true,
    ]);
    $this->progress(5);
    $this->line(PHP_EOL.'<info>✔</info> Success! Your database is set up and configured.');
 }
```

Now when trying to install on a blank database, errors pop stating that there is no users table, because we haven't migrated anything. Was this something you planned on re-adding after you refactored the command?

**Comment by reliq** [comment]
@austintoddj yes. I should have added back those lines. I'll do it now.
