### ISSUE TITLE
new user registrations

### ISSUE THREAD

**Issue by isbkch** [cnvs/easel#109]
Are there plans for opening the blog to multiple user registration and posting in the future ?

**Comment by austintoddj** [comment]
As of right now, new users are only added through the backend by an existing Administrator, is that what you're referring to? Or are you wondering if user registration would be made public?

**Comment by isbkch** [comment]
I'm more concerned opened to the public so people can write stories as well

**Comment by austintoddj** [comment]
Well, it was designed to be a blog managed by an Admin or a few admins, and users can be added with lower levels of privileges. If there was a public registration, they would be able to jump into your blog and change/modify anything you've written. I don't believe the majority of users would want that as a feature on their blog. But it's an interesting concept nonetheless.
