### ISSUE TITLE
Seeding bug on fresh install

### ISSUE THREAD

**Issue by austintoddj** [cnvs/easel#11]
On the `develop` branch, with everything set up and working as it should, a fresh `canvas:install` will not seed:

 * `posts` table
* `tags` table
* `post_tag` table

**Comment by austintoddj** [comment]
Line 78-83 of `Install.php` no longer need to be surrounded by the if() statement, since that was a simple workaround to help the old application ignore seeding if the tables already existed, trying to work on an upgrade process back then. So when we remove those, we still get the following error:

```
 [ReflectionException]                       
 Class Canvas\DatabaseSeeder does not exist
```

Thoughts?

**Comment by reliq** [comment]
This is fixed by https://github.com/cnvs/canvas/commit/1b100279f466ee6692bc571981ae87671e366560.
