### ISSUE TITLE
Current version installed

### ISSUE THREAD

**Issue by austintoddj** [cnvs/easel#12]
During `canvas:install`, line 109 of `CanvasCommand.php` sets the installed version of Canvas in the database from the blog config file. It looks however like we have config file in Canvas, and a config file in Easel, somehow causing the end result of the version stored in the database being `v2.2.x` at the time of this writing. Is it perhaps just not merging the config files properly?

**Comment by reliq** [comment]
@austintoddj I set that to a general version. I think we have to devise a way of getting the current version installed from composer instead of relying on setting this by hand. It feels like this should be automatic since composer always knows.

**Comment by austintoddj** [comment]
I agree. The only reason I was hardcoding it before was because I couldn't think of a better way to grab it. I'm all for automation.

**Comment by austintoddj** [comment]
Fixed with c774f1f3553bfa801daa466ff28bb4cba418ccc2

Fetching of the latest release is done via the GitHub API in the `canvas:install` command. This should safeguard us from having users hit the API rate limit because they'll essentially only be using this command one time.
