### ISSUE TITLE
[EASY] Update link from GitHub to Twitter

### ISSUE THREAD

**Issue by austintoddj** [cnvs/easel#127]
**"Why not change it yourself?"**

I can only assume that some out there will ask why I bothered to create an issue out of such a small change, and why not just change it myself in 2 seconds?

The answer is simple: *I want to get as many developers out there as possible to begin contributing to open source projects*, even if it's something as trivial as this.

----

Line 189 of `src/Console/Commands/Install.php` needs an update to point to the new Twitter account instead of generically pointing to GitHub.

*Old line*:
```php
$this->line(PHP_EOL.'For help, please visit cnvs.readme.io. Follow us on GitHub at github.com/cnvs.'.PHP_EOL);
```

*Updated line*:
```php
$this->line(PHP_EOL.'For help, please visit cnvs.readme.io. Follow us on Twitter at twitter.com/cnvs_io.'.PHP_EOL);
```

If you're already a contributor, then thank you! If this is your first PR to this project or ANYTHING open source, then **Welcome**!

**Comment by DanielFurmanov** [comment]
@austintoddj Hi, please close fixed issues. I just spend couple of minutes staring at the line which you asked to change just to see that it is changed. Then I went back to this issue **and scrolled page down** just to see that it was already fixed. Not cool :)

**Comment by austintoddj** [comment]
@DanielFurmanov FYI the little Information symbol here tells you that the code has been fixed, but the issue closes itself automatically after the commit has been merged into the `master` branch. It's currently only in `develop` because the next release isn't ready yet. 

I understand your frustration, I'll go ahead and manually close the ones I can. But just for your reference, issues close themselves if referenced properly in a commit message and then merged to `master`.

**Comment by DanielFurmanov** [comment]
@austintoddj I meant no offence. Thats the point - the issue description is long enough for me to not see this area without scrolling.

Didn't know about issues auto-closing, also forgot about two dev and master branches approach, sorry!

If you will have any other issue like that - mention me, please. Would like to take part in the project.

**Comment by austintoddj** [comment]
Will do @DanielFurmanov, I'll ping you of any more like these 👍
