### ISSUE TITLE
show image in media

### ISSUE THREAD

**Issue by lchhieu** [cnvs/easel#136]
It is inconvenient for me to click on picture to see it. You can show it if it's an image

**Comment by austintoddj** [comment]
Thanks for checking out Canvas @lchhieu! Could you be a bit more descriptive on what this issue is about? Perhaps a screenshot or a bit more information?

**Comment by lchhieu** [comment]
![image](https://user-images.githubusercontent.com/11382616/26882354-5e56c3ac-4bc4-11e7-9497-909522df48a2.png)
will be easy to see if the image is displayed.  i don't known how to edit your media and run gulp to render new vendor.js

**Comment by austintoddj** [comment]
Hm looks like you may be talking about the [Media Manager](https://github.com/talvbansal/media-manager). @talvbansal maybe you could weigh in on this question?

**Comment by lchhieu** [comment]
You seem to have included all files js as a vendor.js file so I can not edit it.

**Comment by talvbansal** [comment]
So my biggest concern with doing this is the following:  Say within a folder you had 100 images each at approximately 500kb each. You'd be downloading 50mb of data just to view a folder. 

The obvious solution would be generate thumbnails, the complexity comes from managing the thumbnails when items are moved or deleted and what about none images that don't have thumbnails, we'd need code that handled those too.

If anyone has an alternative idea / solution id love a PR to be submitted over on the [Media Manager Repo](https://github.com/talvbansal/media-manager).

**Comment by austintoddj** [comment]
Thanks for jumping in with that @talvbansal. @lchhieu I'm going to close this and let any future discussion for it happen over on the [Media Manager](https://github.com/talvbansal/media-manager) repo since it is specific to it's functionality. 

Any more suggestions or input you have on Canvas is greatly appreciated!
