### ISSUE TITLE
Media Manager Upgrade Bug

### ISSUE THREAD

**Issue by austintoddj** [cnvs/easel#139]
@talvbansal Just merged in the PR that updates the media manager, but if you check out the `develop` branch right now, do you get the same error that I do? 

<img width="1210" alt="screen shot 2017-06-16 at 1 16 34 pm" src="https://user-images.githubusercontent.com/8037011/27239383-4c877a1c-5296-11e7-87a3-fd9ff2a9a51f.png">

## UPDATE:
Currently, when installing the latest release of Canvas, not even develop, the media manager is throwing errors.

**When creating a new folder, you see the following:**
<img width="940" alt="screen shot 2017-06-22 at 8 26 48 pm" src="https://user-images.githubusercontent.com/8037011/27462876-6e39d0f4-5789-11e7-8c99-c25ea0c9617b.png">

**When trying to delete a folder, you see the following:**
<img width="611" alt="screen shot 2017-06-22 at 8 27 20 pm" src="https://user-images.githubusercontent.com/8037011/27462888-7c33ec80-5789-11e7-8056-fec242547e01.png">

**When trying to upload a file, you see the following:**
<img width="220" alt="screen shot 2017-06-22 at 8 27 09 pm" src="https://user-images.githubusercontent.com/8037011/27462895-87df5a74-5789-11e7-9fd7-fe1ee2daebf6.png">

Checked the routes using `php artisan route:list` and nothing looked odd. So these errors are currently in the `2.0` version of Media Manager. Could you confirm @talvbansal?

**Comment by austintoddj** [comment]
Any thought on this @talvbansal?

**Comment by talvbansal** [comment]
Sorry for the delay I've just only just got around to looking at this.


The 404 request we're now seeing is coming from the media-manager making requests to this endpoint:

`/admin/browser/index?path=/`

Looking though the output of `php artisan route:list` I can see that the routes for canvas are being prefixed with admin again:

```
|        | DELETE    | admin/admin/browser/delete           |                                             | \TalvBansal\MediaManager\Http\Controllers\MediaController@deleteFile      | checkForMaintenanceMode,canvasInstalled,auth:canvas              |
|        | GET|HEAD  | admin/admin/browser/directories      |                                             | \TalvBansal\MediaManager\Http\Controllers\MediaController@allDirectories  | checkForMaintenanceMode,canvasInstalled,auth:canvas              |
|        | POST      | admin/admin/browser/file             |                                             | \TalvBansal\MediaManager\Http\Controllers\MediaController@uploadFiles     | checkForMaintenanceMode,canvasInstalled,auth:canvas              |
|        | POST      | admin/admin/browser/folder           |                                             | \TalvBansal\MediaManager\Http\Controllers\MediaController@createFolder    | checkForMaintenanceMode,canvasInstalled,auth:canvas              |
|        | DELETE    | admin/admin/browser/folder           |                                             | \TalvBansal\MediaManager\Http\Controllers\MediaController@deleteFolder    | checkForMaintenanceMode,canvasInstalled,auth:canvas              |
|        | GET|HEAD  | admin/admin/browser/index            |                                             | \TalvBansal\MediaManager\Http\Controllers\MediaController@ls              | checkForMaintenanceMode,canvasInstalled,auth:canvas              |
|        | POST      | admin/admin/browser/move             |                                             | \TalvBansal\MediaManager\Http\Controllers\MediaController@move            | checkForMaintenanceMode,canvasInstalled,auth:canvas              |
|        | POST      | admin/admin/browser/rename           |                                             | \TalvBansal\MediaManager\Http\Controllers\MediaController@rename          | checkForMaintenanceMode,canvasInstalled,auth:canvas              |
```
The short fix is to take the media-manager out of the route:group that adds the additional `admin` to the urls but its not really desirable as it will lead to inconsistency  with end points across canvas.

When we last spoke about configurable routes for the media manager I didn't think it would be possible however I think it might be possible now by passing a "prefix" value down to the media-manager component:

```
<media-modal v-if="showMediaManager" @media-manager-close="showMediaManager = false">
<media-manager
        :is-modal="true"
        :selected-event-name="selectedEventName"
        :route-prefix="/"
        @media-manager-close="showMediaManager = false"
                                           >
</media-manager>
```
And then using that prefix value passed along to all sub components of the media-manager which should solve all the JS issues.

As the media-manager new has an optional config file as part of this change set we'd have to set the `route-prefix` value there to handle the php changes.

I'm currently recovering from surgery atm so im not sure how quickly i could work on this but if anyone fancies tackling it over on the [https://github.com/talvbansal/media-manager](https://github.com/talvbansal/media-manager) repo id be grateful. It really shouldnt be that difficult.

**Comment by austintoddj** [comment]
Awesome thanks for the update @talvbansal. Hope you get better soon!

**Comment by austintoddj** [comment]
@talvbansal Everything looks good on my end, closing this out. 👍
