### ISSUE TITLE
Roles fillable?

### ISSUE THREAD

**Issue by robertem128** [cnvs/easel#144]
This is more of a question then anything else but should 'role' in the User model be filliable? I was under the impression that this could pose a security risk.

**Comment by austintoddj** [comment]
@robertem128 Well, the role can be updated by an Admin User in the application, so the model property needs to be fillable. Are you thinking of something I'm not?

**Comment by robertem128** [comment]
Sorry, didn't see your reply.

I'm by no means an expert but thought it should be guarded and assigned manually (i.e. not using fill) or done through a model observer.

Again, I could be wrong, but couldn't a user modify the request and change their role to Admin as you are using the fill command to update?

**Comment by austintoddj** [comment]
Hm, I perhaps it might be possible. I'd have to see the exact workaround however, because I feel like the application would protect against that. If you're able to do that, let me know.

**Comment by austintoddj** [comment]
Closing this out because I think it's a good thing to note, but no action needs to be done at this time.
