### ISSUE TITLE
Route [canvas.home] not defined. 

### ISSUE THREAD

**Issue by azorpax** [cnvs/easel#147]
i have just followed the instructions from https://cnvs.readme.io/v3.2/docs/integrating-canvas-in-an-existing-project 

i have no idea whats wrong. 
when i go to /admin. i am redirected to my main login page (not from canvas login page). i tried /auth/login then i get error 
"Session store not set on request. (caused by the {{ old('email') }}). i  have removed it and then i get new error  Route [canvas.home] not defined. from the  "<a href="{!! route('canvas.auth.password.forgot') !!}" "

im using laravel 5.3

**Comment by austintoddj** [comment]
Thoughts on this @reliq?

**Comment by reliq** [comment]
@austintoddj , @azorpax this sounds like there may be another route defined at `/admin` within the application. 

See https://cnvs.readme.io/v3.2/docs/integrating-canvas-in-an-existing-project#section-routing

Ensure that you have no conflicting routes. Use `php artisan route:list` from the terminal to see what routes are defined.

**Comment by azorpax** [comment]
No conflicting route for /admin. I even changed the admin prefix to /canvas. Still the same behavior,it will redirect me to my main login page. 

I also checked the route:list. I can't find the canvas.home

**Comment by reliq** [comment]
Hmm, I see. 

You may try re-defining the `canvas.home` route at the end of your application's `routes/web.php`. Similar to: 
```php
Route::get('/some-address', 'Canvas\Http\Controllers\Frontend\BlogController@index')->name('canvas.home');
```
**or**

You may also try changing the blog path in canvas' config file.

eg. 
```php
/*
  |--------------------------------------------------------------------------
  | Canvas Configuration : Blog Prefix
  |--------------------------------------------------------------------------
  |
  | Main prefix for blog.
  |
  */
    'blog_prefix' => 'myblog',
```

---
One of these methods should at least remove the `canvas.home` error.

Let us know if nothing changes.

Cheers :beers:

**Comment by azorpax** [comment]
I added the Route::get('/some-address', 'Canvas\Http\Controllers\Frontend\BlogController@index')->name('canvas.home'); to my main router and then i tried to open /auth/login
and its fine, but when i add back the {{ old('email') }} to the email field. i get this error "Session store not set on request."

i also have this 'admin_prefix' => 'canvas',
when I access the /canvas I am redirected to the main login, not the canvas login (/auth/login).

**Comment by azorpax** [comment]
I have no problem with /blog or /myblog as your suggestion. I can view the page of articles.
 what I'm having trouble is accessing the backend (admin side)

**Comment by azorpax** [comment]
i tried to create a new laravel 5.3 project. fresh install.  just to check if its working. i followed the instructions from https://cnvs.readme.io/v3.4/docs/integrating-canvas-in-an-existing-project but i get the same error from my previous project.

**Comment by azorpax** [comment]
up

**Comment by reliq** [comment]
I'm sorry for the delayed response @azorpax. 

We will have to look into this routing issue in further detail. Usually the `Session store not set on request.` error occurs when one or more of your interacting routes are not defined within the `web` middleware.

The responses to this question may shed some light: https://stackoverflow.com/questions/34449770/laravel-session-store-not-set-on-request

:beers: cheers!
