### ISSUE TITLE
Laravel Mix

### ISSUE THREAD

**Issue by austintoddj** [cnvs/easel#152]
@talvbansal Just pulled in the changes you made, but am running into an issue with the manifest file now being found. If you pull the `l5.4` branch of Easel into Canvas, you'll get this error. Wanna take another PR for it? Also, are all the fonts/assets stuff supposed to be in the root directory like they are?

<img width="1068" alt="screen shot 2017-10-04 at 8 38 21 pm" src="https://user-images.githubusercontent.com/8037011/31207502-30142fce-a944-11e7-93f7-d2e74cc20584.png">

**Comment by talvbansal** [comment]
Ahh ive just had a thought about this - we've removed the versioning in this however we're still using the mix helper.

I'll hopefully be able to look into this tomorrow

**Comment by talvbansal** [comment]
Can we close this now?
