### ISSUE TITLE
Public assets missing

### ISSUE THREAD

**Issue by austintoddj** [cnvs/easel#16]
@reliq Looks like during the extraction of the core from Canvas to Easel, some public assets didn't get updated. The Not Found errors from the backend of the site look like this:

![screen shot 2016-12-05 at 8 24 00 am](https://cloud.githubusercontent.com/assets/8037011/20888402/6eb3b368-bac4-11e6-9d30-930e12f418ad.png)

**Comment by reliq** [comment]
@austintoddj I'll have a look when I get a chance.

**Comment by reliq** [comment]
@austintoddj I didn't get missing _map_ file errors. I found that only _select.png_ was missing.

Please update _easel_ and ensure that core public files are published: `php artisan canvas:publish:assets -f`.

**Comment by austintoddj** [comment]
Do the publishing of core public files only need to be done during development like this? Or is there another reason for the publishing commands?

**Comment by reliq** [comment]
They can be used at any time by us or the end-user. 

Note though that existing files are only overwritten if the `--force` option `-f` is set.
