### ISSUE TITLE
Issue with Installing Canva

### ISSUE THREAD

**Issue by RockaFela** [cnvs/easel#161]
I get the response below from my terminal whilst trying to install the canvas application, I ahve made al necesary adjustments but issues persists 

An unexpected error occurred. Installation could not continue. command not found
ied for user 'root'@'localhost' (using password: NO) (SQL: select * from information_schema.tables where table_schema = canvas and table_name = migrations)

**Comment by austintoddj** [comment]
@RockaFela Is your database created and your credentials stored correctly in the `.env` file?
