### ISSUE TITLE
Error install Canvas version 3.4.4: count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by bvbunnik** [cnvs/easel#162]
Whilst installing Canvas version 3.4.4 (latest at the time of writing) I encounter an error:
```
An unexpected error occurred. Installation could not continue.
[✘] count(): Parameter must be an array or an object that implements Countable
```
![capture](https://user-images.githubusercontent.com/443751/33210471-44f18928-d112-11e7-9415-19b4b26e4c32.PNG)

Tried to run ```php artisan canvas install``` again to no avail. Also completely removing the whole project (directory) and database and starting afresh did not solve this issue...

Anyone encountered this before? I have no idea where the error is coming from.

Any help is appreciated, if more info is needed, please let me know!

**Comment by glennmcewan** [comment]
Are you using PHP 7.2? If so, that will be the issue. PHP 7.2 introduced a kind of breaking change in that calling `count()` on a null yields an error, unlike in previous versions where it would return 0.

If you're on 7.2 let me know and I'll look into fixing this over the weekend.

**Comment by bvbunnik** [comment]
Thanks for your answer!
Indeed I'm using PHP 7.2. I will change versions for now and see if that solves the issue, but indeed the issue should probably be fixed for future versions!

**Comment by glennmcewan** [comment]
Glad that fixed it. I've done a bit of testing locally - the root cause is actually in Laravel itself (`vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:1231`).

Canvas currently uses Laravel 5.3 which does not support PHP 7.2. Laravel 5.5 _seems_ to.

Best case _for now_ is to use this project on 7.1 as the highest dependency, as Laravel 5.3 and the latest Canvas release both support it.

I'll look into setting the maximum PHP version for Canvas to 7.2 in the composer.json file, to hopefully help highlight this restriction.

**Comment by austintoddj** [comment]
Thanks for jumping in @glennmcewan.

**Comment by itzJustKranker** [comment]
is there a fix as of right now besides downgrading php versions or will this issue be addressed in future versions of canvas.....?

**Comment by jdunk** [comment]
laravel 5.3 is quite old now. Seem canvas did not upgrade when 5.4 came around, nor 5.5, nor 5.6. Does canvas have any plans to stay current with its main dependency?

**Comment by 1295** [comment]
Trying to use Canvas now, Same error.
Is downgrading my php version the only solution?

**Comment by jdunk** [comment]
Last commit was > 10 months ago. That should tell is all we need to know (Canvas is dead). I'm out.

**Comment by talvbansal** [comment]
@jdunk @jjdelarosa - I can try to take a look at this in the next few days I'm just travelling at the moment and will be back home next week.
