### ISSUE TITLE
composer require cnvs/easel not installing the latest v3.4.3

### ISSUE THREAD

**Issue by gohlx** [cnvs/easel#167]
Step:
composer require cnvs/easel

Result:
Installing cnvs/easel (v3.4.2): Downloading (100%)

Expected Result:
Installing latest v3.4.3

I notice the latest version is tagged as vv3.4.3
Not sure is it due to tagging error?

**Comment by reliq** [comment]
Hi @gohlx,

Thanks for reporting this. This issue should be resolved shortly. 

Please try again later and confirm.

🍻
