### ISSUE TITLE
can't install using php artisan canvas:install

### ISSUE THREAD

**Issue by protected22** [cnvs/easel#168]
I can't install using php artisan canvas:install

my CMD on windows 7 gives this error: 

SQLSTATE{2002} Can't connect because the pc blocks the conection. 
<SQL: select * from information_schema.tables where table_schema = canvas and table_name = migrations)

**Comment by jgarcia3327** [comment]
change db host from localhost to 127.0.0.1, this solved my issue...

**Comment by jjdelarosa** [comment]
> I can't install using php artisan canvas:install
> 
> my CMD on windows 7 gives this error:
> 
> SQLSTATE{2002} Can't connect because the pc blocks the conection.
> <SQL: select * from information_schema.tables where table_schema = canvas and table_name = migrations)

Go to my repo https://github.com/jjdelarosa/canvasfixed
