### ISSUE TITLE
canvas:install getTablePrefix() bug

### ISSUE THREAD

**Issue by austintoddj** [cnvs/easel#38]
Am I the only one getting this error? 

<img width="623" alt="screen shot 2016-12-20 at 7 37 03 pm" src="https://cloud.githubusercontent.com/assets/8037011/21374364/d02a331e-c6eb-11e6-8d99-8ba64bdc7076.png">

Every time I try to run `canvas:install` or `canvas:update` from the `develop` branch I hit this error.

**Comment by reliq** [comment]
This is related to the version of scout that was being used. I added a catch for the exception in a previous commit in case it arises again.

**Comment by austintoddj** [comment]
Awesome thanks @reliq!

**Comment by austintoddj** [comment]
Yeah this error is so random it's maddening. 😠

**Comment by austintoddj** [comment]
Ran the installer this morning after last night's commits. Still hit the error 3 different times. The 4th run of the installer finally let everything go through.
Run 1:
![screen shot 2016-12-22 at 6 42 51 am](https://cloud.githubusercontent.com/assets/8037011/21425999/14a6e6be-c812-11e6-8901-4243145aef5f.png)

Run 2:
![screen shot 2016-12-22 at 6 43 01 am](https://cloud.githubusercontent.com/assets/8037011/21426003/18a6c018-c812-11e6-9858-fe5c787570a5.png)

Run 3:
![screen shot 2016-12-22 at 6 43 14 am](https://cloud.githubusercontent.com/assets/8037011/21426006/1cca00ec-c812-11e6-9deb-7801724209a9.png)

**Comment by austintoddj** [comment]
Ok, so the buggy line is:

- `vendor/teamtnt/laravel-scout-tntsearch-driver/Engines/TNTSearchEngine.php` line 199

An example of the misbehavior is the following image:

![screen shot 2016-12-22 at 8 03 13 am](https://cloud.githubusercontent.com/assets/8037011/21427965/259261f0-c81d-11e6-9051-e702260d83d4.png)

Seems like you have to index the thing once, hit the error, and then re-run to pass it.

**Comment by reliq** [comment]
Good catch @austintoddj. I had stopped seeing the error. Weird

**Comment by nticaric** [comment]
https://github.com/teamtnt/laravel-scout-tntsearch-driver/releases/tag/v2.0.0 hopefully this version fixes that

**Comment by austintoddj** [comment]
Thank you for doing this @nticaric! I'll give it a shot shortly. @reliq and @talvbansal if you guys want to test it on your end too that'd be good.

@nticaric Did this 2.0.0 release include support for Scout v2.0?

**Comment by austintoddj** [comment]
@nticaric Looks like with the latest release pulled in, the installer simply hangs indefinitely, never completing anything. Perhaps there is a tweak to be made?

**Comment by austintoddj** [comment]
Ran the installer with the latest update and it worked! Thanks @nticaric!!

**Comment by austintoddj** [comment]
Resolved with commit: https://github.com/cnvs/easel/commit/0f7cef81948d98653e8e37247d5ce2d02c098247
