### ISSUE TITLE
Route names everywhere

### ISSUE THREAD

**Issue by reliq** [cnvs/easel#41]
We should refer all links throughout canvas by route names instead of raw paths. This would allow canvas to be more configurable; one may then opt to have canvas serve from a path other than the main site url. 

eg: *mysite.com/**blog*** or *mysite.com/**articles***.

This configuration is supported since @8274eb9fc892a5c1e7e7ae2a76ee867ce76e1631. However, all or most url's in canvas are currently referred to by path and will result in a `404` response.

**Comment by austintoddj** [comment]
Good thought @reliq. So now it's just a matter of finding all the links in the app and update them to use the named route?

**Comment by reliq** [comment]
@austintoddj yes

**Comment by austintoddj** [comment]
@reliq Since you know more of what you were envisioning with this feature, would you care to update the links you're referring to throughout the project? Just want to make sure I don't miss something you're thinking of.

**Comment by reliq** [comment]
@austintoddj alright, but this will take a while.

**Comment by austintoddj** [comment]
Thanks for doing this @reliq 👍

**Comment by reliq** [comment]
@austintoddj I ran into one instance which would prevent allowing users to modify the `admin` routes. This is with `TalvBansal\MediaManager\Routes\MediaRoutes`. The url's are hard-coded in JS and do not seem customizable.

As you would see in `RouteHelper.php` on line 62, there is provision to allow customizing admin routes but  because of the foreseen errors regarding the hard-coded media manager aspects (mentioned above) I have removed the option from the `config/blog.php` file. So the end-user cannot customize admin routes the easy way at this time.

What are your thoughts on this?

**Comment by austintoddj** [comment]
Ah, I did not think of that. I really liked the direction you were going with the routes because eventually I'd love to see https://github.com/cnvs/canvas/pull/171 as a new feature. 

@talvbansal, any way we can work with the Media Manager routes that you see?
