### ISSUE TITLE
Media Manager Internal Server Error

### ISSUE THREAD

**Issue by austintoddj** [cnvs/easel#42]
Don't know if you've seen this issue on Easel yet, but on a fresh install of Canvas, the Media Manager doesn't seem to be functional. Tried adding a folder, but it won't save a new one. Trying to upload an image results in an `Internal Server Error` message.

**Comment by talvbansal** [comment]
Fixed on cnvs/canvas develop branch, some removed the storage/app/public folder that's needed to be linked to public/storage.

**Comment by reliq** [comment]
@austintoddj remember the installer does the linking so maybe this is related to the installation not going smoothly.

**Comment by austintoddj** [comment]
@reliq You're right, totally forgot about that. Perhaps that's the source of this issue @talvbansal?

**Comment by talvbansal** [comment]
Its not, the link:storage command makes a symlink bwtween from a storage/app/public folder and public storage, if storage/app/public doesn't exist the link cant be created.

Also if you look at the laravel/laravel repo that folder exists and the .gitignore file is as per my commit
