### ISSUE TITLE
Publish view files conditional

### ISSUE THREAD

**Issue by austintoddj** [cnvs/easel#43]
On line 75 on `Install.php`, there's an *if* statement only allowing the publishing of views if a flag is passed through with the command. In my experience running the past dozen installs, the view files are never published on `canvas:install`. I believe the config files and asset files publish just fine, but the view files however remain excluded.

My question is, can we remove this conditional if statement? Or is there a way to make sure the view files will absolutely be published on install?

A way to replicate the issue and see the error I am seeing is to:

- Clone a fresh copy of Canvas
- Switch to the develop branch
- Run `composer install`
- Run `canvas:install`
- Access the login page from a browser and submit the form without inputing any info, the javascript validation should merely highlight the underlines of the inputs. A blade view contains some CSS hiding the textual error messages, so you should not see them.

**Comment by reliq** [comment]
@austintoddj it is not imperative that the views are published as views are loaded directly from the package. The ability to publish views is there for when the end-user wants to *customize* a package's view(s). 

---

When Laravel attempts to resolve a package's views, by design, it checks the `views/vendor` folder to see if a customized version of said view exists, if it doesn't exist it loads the view from the location specified in the *ServiceProvider*. In our case, line 88 in _CanvasServiceProvider_: 
`$this->loadViewsFrom(__DIR__.'/../resources/views', 'canvas');`

Therefore whether views are _published_ or not should not interfere with CSS/JS.

Ideally we do not want to publish views on install as it is optional and dependent on the use-case.

Official wording: https://laravel.com/docs/5.3/packages#views

---

*PS:* The *theme* mechanism utilizes this feature.

**Comment by austintoddj** [comment]
Ok that's a good explanation. But if you run through the steps I detailed above, do you see the same errors that I do? I am only able to solve it by manually running canvas:publish:views

**Comment by reliq** [comment]
On a fresh install I'm stuck at `✘ SQLSTATE[HY000] [14] unable to open database file` at the "Creating your database..." stage. This seems unrelated.

Maybe it's my setup, I'll try again later.

**Comment by austintoddj** [comment]
Hm odd. Let me know if that error persists.

**Comment by austintoddj** [comment]
@reliq Just did a couple fresh installs, didn't run into that error. Are you still hitting it?

**Comment by reliq** [comment]
@austintoddj haven't seen it since.

**Comment by austintoddj** [comment]
Good, glad it isn't persisting. Would you be able to take a quick look at the issue described above with the steps I listed out?

**Comment by austintoddj** [comment]
@reliq Here is a full guide to how I can reproduce the issue we were discussing last night.

**Complete steps to reproduce the issue:**

- Clone a fresh copy of Canvas: `git clone git@github.com:cnvs/canvas.git`
- Switch to the develop branch: `git flow init`
- Run composer install: `composer install`
- Create a new `.env` file: `cp .env.example .env`
- Install: `php artisan canvas:install`
- Go to the `/admin` page (Should see the login form)

*Without inputting  anything in either field*, click `Sign In`. You should see this validation:

![screen shot 2016-12-29 at 7 29 03 am](https://cloud.githubusercontent.com/assets/8037011/21544953/2e6ab15c-cd99-11e6-9df6-3a317bb1695f.png)

The above screenshot is **what we don't want.**

- From your terminal, run `php artisan canvas:publish:views`
- Refresh the `/admin` page, and click `Sign In` without any of the fields filled out. you should now see the _correct validation_:

![screen shot 2016-12-29 at 7 29 20 am](https://cloud.githubusercontent.com/assets/8037011/21544981/646bf928-cd99-11e6-9f72-b22ed02d575c.png)

**Comment by reliq** [comment]
@austintoddj the error seems to have been due to an incorrect class reference. commit https://github.com/cnvs/easel/commit/34026c466ed5b35f6276c15784b7d04791e0fcba, fixes this. 

I have no idea why the class wouldn't be exactly the same whether views are published or not. It could be related to the _JS validation_ plugin, but I have no idea how that works so this statement is a blind assumption.

**Comment by austintoddj** [comment]
Thanks for taking a look at this @reliq. I'll check it out first thing tomorrow morning.

**Comment by austintoddj** [comment]
Since the installer is the first thing any user will hit when grabbing Canvas, and it will *never be run again*, I think we're ok to simply publish views with the installation.

**Comment by reliq** [comment]
@austintoddj it is for this exact reason why we shouldn't publish views on install. 

If we publish an update which changes in a particular view file; the user would need to publish views to get the updated view files, losing whatever custom view changes they made themselves.

**Comment by austintoddj** [comment]
@reliq I guess I don't see what you mean here. The commit I pushed makes it so the issue doesn't appear anymore, don't know how to make it so we don't see the error and still have the same install command you set up.

**Comment by reliq** [comment]
OK. I'll have a look at it.

**Comment by austintoddj** [comment]
@reliq your last commit, did that change the behavior on your end? Just pulled down the latest and ran a fresh install, didn't see any different behavior. For instance on the dashboard home page when a user logs in, click the Publish button for a quick draft post and the page should scroll to those field errors. Not currently seeing the scroll happening.

**Comment by austintoddj** [comment]
Never mind @reliq! Found my error. Super simple. Going to make the change and be done with this issue 👍

**Comment by reliq** [comment]
@austintoddj that last commit you did (https://github.com/cnvs/easel/commit/9056c8b5fd25282fdb51f3145cfd69b044ea1871), is the exact opposite and actually undid the fix (https://github.com/cnvs/easel/commit/8a227816b98f5653d50658e76038230a6f1eec97).

`jsvalidation/bootstrap.php` is a third party file which should be published via its own provider to prevent errors such as the ones we're currently having.

**Comment by austintoddj** [comment]
Fixed with https://github.com/cnvs/easel/commit/3485103ecafefcda50f53760074baadb1d37ddb0
