### ISSUE TITLE
Modify tables and Migrations to allow Seamless Integration into any Laravel Project

### ISSUE THREAD

**Issue by reliq** [cnvs/easel#45]
Since canvas core (Easel) is now a package that can essentially be brought into any Laravel project. I suggest we manually prefix canvas specific tables to allow a more seamless integration with any existing architecture. 

eg.
- settings --> canvas_settings
- posts --> canvas_posts

*NB*: I used _manual_ to mean that we would *not* use the Laravel global table prefixing mechanism (discussed here: https://laracasts.com/discuss/channels/laravel/using-table-prefixes-in-laravel?page=0). This would defeat the purpose since all tables in the project would then have that prefix by default.

I also suggest we modify the migrations for tables that may already exist such as the `password_resets` and `users` tables, to allow creation of the table only if it doesn't exist and; in the case of the `users` table specifically we update the table to add in canvas specific columns if it already exists.

@austintoddj, @talvbansal thoughts?

**Comment by austintoddj** [comment]
I like this idea. No problem with heading in a direction that would make it more accessible to a greater audience of people. 👍

**Comment by austintoddj** [comment]
Looks good here @reliq! Thanks for the addition!

**Comment by austintoddj** [comment]
@reliq With this change, a few things broke on the backend. Saving a new post either through the quick draft section on the home page or just adding a new post on the Posts page throws this error:

<img width="999" alt="screen shot 2017-01-03 at 6 41 46 am" src="https://cloud.githubusercontent.com/assets/8037011/21608108/0d7988de-d180-11e6-9439-b5093c88f83a.png">

And saving a new tag throws this error:

<img width="995" alt="screen shot 2017-01-03 at 6 42 06 am" src="https://cloud.githubusercontent.com/assets/8037011/21608112/1be38c8a-d180-11e6-82bd-9a3d5c6f8b7d.png">

As well as deleting a user will throw an error. Those are just the parts I found so far, there could be more.

**Comment by austintoddj** [comment]
Should be all fixed up now, just had some spots where the `CanvasHelper::TABLES` constant needed to be called. 👍

**Comment by reliq** [comment]
@austintoddj cool.
