### ISSUE TITLE
Custom route configuration

### ISSUE THREAD

**Issue by austintoddj** [cnvs/easel#47]
Per our discussion in #41:

@reliq brought up the point:

> @austintoddj I ran into one instance which would prevent allowing users to modify the admin routes. This is with TalvBansal\MediaManager\Routes\MediaRoutes. The url's are hard-coded in JS and do not seem customizable.
> 
> As you would see in RouteHelper.php on line 62, there is provision to allow customizing admin routes but because of the foreseen errors regarding the hard-coded media manager aspects (mentioned above) I have removed the option from the config/blog.php file. So the end-user cannot customize admin routes the easy way at this time.
> 
> What are your thoughts on this?

@talvbansal Can you think of any way we could let the Media Manager play nicely with custom route configuration in Canvas?

**Comment by talvbansal** [comment]
I'll have to have a longer think about this, as @reliq rightly says the route names are coded in JS and then webpacked and therefore (at least to me) not going to be configurable using php. 

Even if i added route names to the `TalvBansal\MediaManager\Routes\MediaRoutes` file I dont think tat the javascript would have no way of picking those route names up?

I'm definitely open to suggestion on this if anyone can think of a way around it?

**Comment by austintoddj** [comment]
@reliq Is this something that will prevent our v3.0.0 release? If not, I'll move this discussion off the current release schedule and we can further explore our options on it.

**Comment by reliq** [comment]
@austintoddj we could leave it out for now since the config to change the admin routes is not currently being published (in `config/blog.php`).

**Comment by talvbansal** [comment]
Looks like this could be continued on now that we have at  least configurable prefixes for the media-manager
