### ISSUE TITLE
Enabling maintenance mode HTTP Exception

### ISSUE THREAD

**Issue by austintoddj** [cnvs/easel#52]
When enabling maintenance mode from the `admin/tools` page, you will hit the following error when trying to access the front page of the blog in a Private/Incognito browser window:

<img width="994" alt="screen shot 2017-01-02 at 9 48 23 pm" src="https://cloud.githubusercontent.com/assets/8037011/21599632/72cee63e-d135-11e6-951d-f0a616c02373.png">

**Comment by austintoddj** [comment]
@reliq I believe this may have something to do with how routes are handled now. Could you take a look at `src/Http/Middleware/CheckForMaintenanceMode.php` and let me know what you think?

The gist of what is supposed to happen is whoever enables Maintenance Mode on the site should have their IP whitelisted and be allowed to view the entirety of the site, because they're an Admin. Everyone else should get the Be Right Back page.

**Comment by reliq** [comment]
Ok @austintoddj I will have a look.

**Comment by talvbansal** [comment]
This is because the `errors.503` view now sits under the canvas namespace : `canvas::errors.503`. I'm not sure how you can make laravel use namespaced view for errors but we can fix this quite easily by bringing those error views back into the canvas repo

**Comment by austintoddj** [comment]
Sounds fine to me. Thoughts @reliq?

**Comment by austintoddj** [comment]
This may not be the best way to go about it, don't know if it will break other features in the process, but commenting out 1 line and writing a new one in `CheckForMaintenanceMode.php` makes this work. Let me know @talvbansal or @reliq if this is a bad idea:

```php
public function handle($request, Closure $next)
    {
        if ($this->app->isDownForMaintenance()) {
            $response = $next($request);

            if (in_array($request->ip(), $this->excludedIPs + $this->getExcludedIPs())) {
                return $response;
            }

            $route = $request->route();

            if ($route instanceof Route) {
                if (in_array($route->getName(), $this->excludedNames)) {
                    return $response;
                }
            }

            if ($this->shouldPassThrough($request)) {
                return $response;
            }

//            throw new HttpException(503);
            return response(view('canvas::errors.503'), 503);
        }

        return $next($request);
    }
```

**Comment by reliq** [comment]
@austintoddj since `404` errors are handled by the `App\Exceptions\Handler.php` in the main _canvas_ repo, I think it would be more consistent to apply the fix there. i.e. the following:

````php
case $e instanceof \Symfony\Component\HttpKernel\Exception\HttpException:
                return response(view('canvas::errors.503'), 503);
                break;
````

I added this here: https://github.com/cnvs/canvas/commit/8089554547e18d4ed804be0a165e8b36431bdaef

**Comment by austintoddj** [comment]
Awesome thanks for sending that through @reliq!
