### ISSUE TITLE
On profile don't show Website value

### ISSUE THREAD

**Issue by CesaRamirez** [cnvs/easel#54]
On view profile don't show value for field website.

Reviewing the view `views.backend.profile.partials.form.social-networks.blade.php` input url is not have value.

Set `$data['url']` for working.

**Comment by austintoddj** [comment]
@CesaRamirez The latest release(v3.0.2) is out and should solve this issue. Feel free to close it out when you see it work! 👍

Run `php artisan canvas:update` from a Terminal in your project root to pull in the change.

**Comment by CesaRamirez** [comment]
Great, but I don't see the change on last commit

**Comment by austintoddj** [comment]
@CesaRamirez My mistake, apologies. Made a couple other changes and thought I had put this one in as well. Doing it right now.

**Comment by austintoddj** [comment]
Ok, `v3.0.3` will address your bug. Give it a try!

**Comment by CesaRamirez** [comment]
Yeah! It's Working :+1:
