### ISSUE TITLE
Why are passwords shown when running the install command ?

### ISSUE THREAD

**Issue by adelowo** [cnvs/easel#56]
https://github.com/cnvs/easel/blob/737062061fb3f329c4ded6d51495fc857fefe3d3/src/Console/Commands/Install.php#L104

Shouldn't that be making use of the `secret` method (https://laravel.com/docs/5.3/artisan#prompting-for-input) instead ?

**Comment by talvbansal** [comment]
@adelowo i totally agree! I cant see why anyone would disagree with this suggestion so I'll make this change accordingly

**Comment by adelowo** [comment]
Cool.. Should close this
