### ISSUE TITLE
Error: file_put_contents(): Exclusive locks are not supported for this stream when running canvas:install

### ISSUE THREAD

**Issue by jwhulette** [cnvs/easel#62]
I'm installing Canvas in a Vagrant box. I've had this issue before but I solved it by setting the cache and sessions directory to /tmp and it works on the 5 lavarel projects I have. Any idea why this is occurring?

**Comment by jwhulette** [comment]
The error is coming from this command, canvas:publish:assets

**Comment by austintoddj** [comment]
@jwhulette What are the permissions set on your `storage` directory?

Per Laravel:

```
Directory Permissions

After installing Laravel, you may need to configure some permissions. 
Directories within the storage and the bootstrap/cache directories should be writable by your web server or Laravel will not run.
If you are using the Homestead virtual machine, these permissions should already be set.
```

**Comment by jwhulette** [comment]
Storage directory is 777

**Comment by jwhulette** [comment]
Ok I fixed this issue by modifying vendor/league/flysystem/src/Adapter/Local.php $writeFlags = LOCK_EX to LOCK_SH which allowed for the asset install.
