### ISSUE TITLE
Install Error: SQLSTATE[HY000]: General error: 10 disk I/O error

### ISSUE THREAD

**Issue by jwhulette** [cnvs/easel#63]
I am installing in a Freebsd vagrant box with MySql. Everything is installed correctly. I create the database but I'm getting the error when trying to run the migrations. It appears the error is related to  SQLite but i'm not using that. I have several other vagrant boxes set up the same way and have a no issues running migrations.

**Comment by jwhulette** [comment]
If I edit line 86 in vendor/cnvs/easel/src/Console/Commands/Install.php to say seed equals false, then it creates the tables, if I set it to true then I get the error.

**Comment by austintoddj** [comment]
@jwhulette Could you post a screenshot of what the error is you are receiving?

**Comment by jwhulette** [comment]
![1__default__vagrant__and_install_error__sqlstate_hy000___general_error__10_disk_i_o_error_ _issue__63_ _cnvs_easel](https://cloud.githubusercontent.com/assets/4930051/21984115/5f02c3ae-dbc2-11e6-9ff3-be18e0fb372a.png)

Just to clarify I created a new Canvas application by following, https://cnvs.readme.io/docs and I'm not sure if it makes a diffence but when visiting my page, I get a 404 route not found.

**Comment by jwhulette** [comment]
Ok, I figured out the problem. SQLite, for TNTSearch, does not like the vagrant shared folder using NFS. So I added,         'storage'  => env('SCOUT_STORAGEPATH', storage_path()), to the scout.php file and change the storage location in my .env file.

**Comment by austintoddj** [comment]
Great work @jwhulette. So that fixed the issue?

**Comment by jwhulette** [comment]
@austintoddj Yes, changing the storage path work. I just created a folder in my Apache directory and it put the SQLite files in it. The only other change was to CHMOD 777 on the files to they could be read. I love vagrant, but sometimes it throws me for a loop. :)

**Comment by austintoddj** [comment]
Awesome thanks for documenting what you did here @jwhulette. It'll be helpful for anyone else who runs into this in the future. Feel free to close it out once you deem it resolved.
