### ISSUE TITLE
Forgot password email is broken

### ISSUE THREAD

**Issue by austintoddj** [cnvs/easel#64]
The `Forgot Password` feature of the login page sends out an email correctly, but if you click on the `Reset Password` button in the email you are dropped on a 404 page. Assuming this has something to do with the massive routes change we made a couple weeks ago. Maybe you could take a look at this @reliq?

**Comment by austintoddj** [comment]
@reliq The fix you put in place works great, the password can be reset just fine now. 

However, the email template for some reason is pulling in the default that ships with Laravel. See below:

<img width="1154" alt="screen shot 2017-01-19 at 9 23 37 am" src="https://cloud.githubusercontent.com/assets/8037011/22112577/1324fec0-de29-11e6-87b6-fe0284ea137e.png">

The customized template is found in `resources/views/vendor/notifications/email.blade.php`. See below:

<img width="1134" alt="screen shot 2017-01-19 at 9 23 47 am" src="https://cloud.githubusercontent.com/assets/8037011/22112589/1cafc358-de29-11e6-8c88-8ee81cbcbca7.png">

This used to work just fine, tested it about a week and a half ago. 

So I wonder, without running `php artisan canvas:publish:views` (which would drop the custom template into `resources/views/vendor/...`), how can we update this so that we pull the custom template from Easel?

**Comment by austintoddj** [comment]
Been banging my head against a wall on this one, maybe you have a suggestion @reliq?

The file in Laravel's core that I want to override a method in is `/vendor/laravel/framework/src/Illuminate/Notifications/Messages/MailMessage.php`. 

If there was a way that we could override the following variable `$view`:

```php
/**
     * The view for the message.
     *
     * @var string
     */
    public $view = [
        'notifications::email',
        'notifications::email-plain',
    ];
```

then we could reference our own template in `cnvs/easel/resources/views/vendor/notifications/`.
Let me know what you think.

**Comment by reliq** [comment]
No. We shouldn't edit Laravel's `MailMessage.php`. I actually think we should leave the email/notification views alone since they actually belong to Laravel's notification "package". Let the end-user do whatever they want with that.

I think we can get rid of the `resources/views/vendor` folder altogether.
