### ISSUE TITLE
Messages not linked correctly

### ISSUE THREAD

**Issue by austintoddj** [cnvs/easel#67]
With commit: 4bae15c134fc5a75c0283921ca543d96bde2498f, the messages have not been brought over from Canvas to Easel in a working state. This has affected most of the notifications. 

Let me know if you need any more direction on it, here is an example of the bug:

<img width="358" alt="screen shot 2017-01-16 at 2 34 53 pm" src="https://cloud.githubusercontent.com/assets/8037011/21998310/a6b78ce8-dbf9-11e6-801d-b104bdb87e7a.png">

**Comment by reliq** [comment]
I saw that. Not sure where that's coming from. Will have to take another look...

**Comment by reliq** [comment]
Should be fixed. @austintoddj is this still happening?

**Comment by austintoddj** [comment]
I'll check this out shortly @reliq. Just taking a look at some TravisCI bugs quick.

**Comment by austintoddj** [comment]
Looks good @reliq 👍, thanks for taking a look at it!
