### ISSUE TITLE
Class PostFormFields not found

### ISSUE THREAD

**Issue by austintoddj** [cnvs/easel#7]
**UPDATE:** The error below does NOT appear when installing Canvas through `composer create-project cnvs/canvas`. The error popped up for me when doing a `git clone ...`. Perhaps this has to do with not releasing a tag for it yet?

When running the initial `composer install` in [Canvas](https://github.com/cnvs/canvas), the following error comes up:

<img width="1439" alt="screen shot 2016-11-30 at 9 57 09 am" src="https://cloud.githubusercontent.com/assets/8037011/20759831/c799e3d8-b6e3-11e6-9364-6f899ff5695f.png">

**Comment by reliq** [comment]
Please run `composer update` instead.

`composer install` installs packages from *composer.lock*. **easel** is new, so lock file is outdated. 

`composer update` reads the *composer.json*, downloads the latest packages according to requirements, and *updates composer.lock*.

**Comment by austintoddj** [comment]
Fixed with [a5c7967b](https://github.com/cnvs/canvas/commit/a5c7967b398d79d74a70a364b3cb9a51b1c8dba9)
