### ISSUE TITLE
Canvas:update Command

### ISSUE THREAD

**Issue by austintoddj** [cnvs/easel#8]
I'd like to see a new command under the name of `canvas:update` where users can upgrade their installation of Canvas up to the latest release. This could potentially extract lines 50-103 in `Install.php`, since upon a new install, all assets will need to be published for the app to work.

**Comment by reliq** [comment]
I'll look into this. Needs a bit more thought also.

**Comment by Jeroen-G** [comment]
I suppose you mean update the non-packaged stuff. If it's a git repo it is fairly easy. Otherwise you could perhaps download the update and check if the files are changed by the user before overwriting.

**Comment by austintoddj** [comment]
@reliq 
Ran the update, looks nice! I assume the things I ran into are only occurring because we're just in development, with adjoining directories and such. The first thing that caught my eye was:

- Package "cnvs/easel" listed for update is not installed. Ignoring.
- Then the ambiguous class resolution warning, which I'm assuming end users will never see because there won't be an autoloading conflict like we have.
![screen shot 2016-12-07 at 7 58 26 am_thumb](https://cloud.githubusercontent.com/assets/8037011/21052339/1c9eaadc-bdea-11e6-9e49-04f08db3a06d.png)
- And at the end, don't get any versions, which I'm assuming has something to do with the first issue I saw.

Lastly, how come we need to ask the questions to the user fi they want to update the core or assets? If they are updating, can't we assume they want to update these?

The only reason I am hesitant on the questions is because end users will most likely have no idea what they're supposed to do. If we can do a "question-less" update, that'd be my preferred option. Unless there is too much opportunity for a broken app without them.

**Comment by reliq** [comment]
@austintoddj you're right! Points 1 and 3 are related and are because we aren't actually using the composer version in development.

End users may see the *ambiguous class resolution* warnings because of migration files. This is not a problem. 

The first question is a confirmation. The second could be omitted. I will make the change.

**Comment by austintoddj** [comment]
Awesome thanks for addressing that @reliq. Understandable about the confirmation question. Wish I had a way to get around the warning, it's just ugly and gives the sense of something possibly went wrong. But if nothing can be done..

**Comment by reliq** [comment]
You shouldn't see the warnings in the latest update.

**Comment by austintoddj** [comment]
Awesome @reliq, you're the man! 👍 Great thought with the `--quiet` flag. I think a final end-user who creates a blog from scratch with this will never see this warning because they'll only ever have 1 set of migrations published. And that'll be what Easel publishes for them. That sounds correct right?

**Comment by reliq** [comment]
@austintoddj cool. Composer may still warn about ambiguity, especially after the migrations have been published from Easel. Remember this is because the autoloader sees both the published versions and the original versions. But as I was saying earlier we can ignore those warnings.

**Comment by austintoddj** [comment]
Sorry to keep beating this dead horse @reliq, but found this: https://blog.liplex.de/getting-rid-of-ambiguous-class-resolution-warnings/

What are your thoughts on that?

**Comment by reliq** [comment]
@austintoddj I don't think it's safe for us to delete any folders. So that method wouldn't work for us.

**Comment by austintoddj** [comment]
Ok. I'll keep looking for a solution, it'll give me something to do till we get these tests in place. Thanks for checking the link out.

**Comment by reliq** [comment]
@austintoddj The `--quiet` flag I added actually suppresses those messages so you don't have to find another solution..

**Comment by austintoddj** [comment]
@reliq Thanks! Yeah saw that, and you're right, the end user won't really see that. The only reason I saw that was because I was doing my own composer dump-autoload, which made the warning pop. Your flag will mitigate this issue for normal users 👍

**Comment by austintoddj** [comment]
Resolved with commit b7c826c5b20f6180ade5ba1f9c9464bdf790a218
