### ISSUE TITLE
How to solve this sqlstate error?

### ISSUE THREAD

**Issue by angelfreedomv** [cnvs/easel#80]
echodeMacBook-Pro:blog echopan$ sudo php artisan canvas:install
Password:

Welcome to the Canvas Install Wizard! You'll be up and running in no time...

An unexpected error occurred. Installation could not continue.
✘ SQLSTATE[HY000] [2002] No such file or directory

Migrations were rolled back. Please run the installer again.

If this error persists please consult https://github.com/cnvs/easel/issues.

**Comment by angelfreedomv** [comment]
My environment:
Mac OS 10.12.3
php -v
PHP 5.6.28 (cli) (built: Dec  6 2016 12:38:54) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies

mysql 5.5.42

**Comment by marktopper** [comment]
http://stackoverflow.com/a/20733001/2807030

**Comment by austintoddj** [comment]
@angelfreedomv Did the link above give you any further clarity on the issue?

**Comment by ruchern** [comment]
Try this: `mysqld`

**Comment by RDelorier** [comment]
I've gotten that before when I had the wrong database name in .env

**Comment by austintoddj** [comment]
@angelfreedomv Has the latest update to Easel fixed this issue for you?

**Comment by ruchern** [comment]
Your MySQL might not be started and perhaps that error thrown is because the application is unable to find `mysql.sock`.

**Comment by anish137i** [comment]
Still error showing on XAMPP Environment in Mac but changing localhost to 127.0.0.1 suggested in  http://stackoverflow.com/a/20733001/2807030 is solve problem.
