### ISSUE TITLE
canvas:install

### ISSUE THREAD

**Issue by austintoddj** [cnvs/easel#9]
Like I mentioned in #8, lines 50-103 in `Install.php` seem to be out of place, since a completely new user will be confused as to what needs to be published, or why it isn't done for them, or what granular assets to publish. If there is a way for us to either publish them all or not publish them, I think it would be less confusing. 

Also, and this is a user-flow thing, I want the install to be as painless and quick as possible. Less questions = more people getting the app up and running.

**Comment by reliq** [comment]
This can be updated to only publish *config*, *migrations*, and *public* on install. 

Views are optional, I'm thinking a separate command for this, say `canvas::views`

**Comment by austintoddj** [comment]
I like that idea. Let's go ahead with that.

**Comment by reliq** [comment]
Cool 👍
