### ISSUE TITLE
Support for Laravel 5.4

### ISSUE THREAD

**Issue by sebasspf** [cnvs/easel#97]
Hi, im trying to **add Canvas to a existent application in Laravel 5.4**. All went well, but when i visit the main page, an **error** is showing:

```
ReflectionException in Container.php line 681:
Class checkForMaintenanceMode does not exist
```
¿Is this related to the Laravel Version? ¿Any way to manually fix this? Thanks!!

**Comment by austintoddj** [comment]
Thanks for checking out Canvas @sebasspf! Right now, Canvas only supports Laravel 5.3.*. There are some hurdles that currently hold us back from upgrading. We intend to support 5.4 as soon as possible though!

**Comment by barnc** [comment]
Any idea of a timeframe for 5.4 support? Wondering whether to wait it out or use a different blog solution.

**Comment by austintoddj** [comment]
@barnc Fully intend to add support for Laravel 5.4. Currently, the hold up is with `proengsoft/laravel-jsvalidation`. They have an open pull request at https://github.com/proengsoft/laravel-jsvalidation/pull/224 that provides support for Laravel 5.4. Until I see that merged and closed, we can't move forward in upgrading Canvas, unless we choose to go with another validator. 

So the answer is yes, we intend to upgrade. We are just waiting on Proengsoft to merge this PR and we can get moving on it.

**Comment by barnc** [comment]
Great, makes sense. Thanks for the info @austintoddj

**Comment by shamatov** [comment]
Hi @austintoddj,

Are there any updates regarding Laravel 5.4 support?

Thanks!
